# Generated by Django 5.0.2 on 2024-02-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="")),
                ("createur", models.IntegerField()),
                ("dateCreation", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Objectif",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=100)),
                ("date", models.DateField(null=True)),
                ("statut", models.BooleanField()),
                ("priorite", models.BigIntegerField()),
            ],
        ),
    ]
