# Generated by Django 5.0.2 on 2024-02-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_traduction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="traduction",
            name="traduction",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
